### ISSUE TITLE
mimic3-server: OpenAPI page does not work (Failed to load API definition)

### ISSUE THREAD

**Issue by lithiumsulfate** [MycroftAI/mimic3#6]
**Describe the bug**
The OpenAPI page fails to load with the message "Failed to load API defintion". It also displays the following error:

```
Fetch error
response status is 500 /openapi/swagger.json
```

Additionally, the following error appears in the `mimic3-server` log output:

```
ERROR:mimic3_http.app:
Traceback (most recent call last):
  File "/var/lib/mimic3/venv/lib/python3.9/site-packages/quart/app.py", line 1512, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/var/lib/mimic3/venv/lib/python3.9/site-packages/quart/app.py", line 1557, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/var/lib/mimic3/venv/lib/python3.9/site-packages/swagger_ui/handlers/quart.py", line 27, in swagger_blueprint_config_handler
    return jsonify(doc.get_config(request.host))
  File "/var/lib/mimic3/venv/lib/python3.9/site-packages/swagger_ui/core.py", line 130, in get_config
    assert Path(self.config_path).is_file()
AssertionError
```

This is most likely unrelated to #5, as this issue occurs when accessing the app directly (with default settings, not through a reverse proxy or similar).

**To reproduce**
1. Start a `mimic3-server` instance with the default settings.
2. Navigate to `http://localhost:59125/openapi/`.
3. The error appears and the page fails to load.

**Environment:**
 - Device type: x86_64, aarch64
 - OS: Arch Linux, Arch Linux ARM
 - httpd 2.4.54
 - Python 3.9

**Comment by krisgesling** [comment]
Hmm, will have to dig into this. Thanks for flagging it though!

**Comment by ChrisCarini** [comment]
Also seeing this issue.

**Comment by fivestones** [comment]
Also seeing this issue. @krisgesling Is the complete API documented in the bit mentioned about it at https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mimic-tts/mimic-3#endpoints ? Or is there more to the api? While this bug is being fixed, is there a way to see the full documentation of the api somewhere? I'd love to be able to use things like --process-on-blank-line or adjusting the length scale of a voice, but through the api and I'm not sure if this is possible because of this bug.
Thanks!

**Comment by krisgesling** [comment]
Hey @fivestones sorry I missed your comment.

You can find all the API parameters here: 
https://github.com/MycroftAI/mimic3/blob/master/mimic3_http/swagger.yaml

eg lengthScale is here:
https://github.com/MycroftAI/mimic3/blob/d8fd17720214d0dd56fbfb5a5d954dfed68c03dc/mimic3_http/swagger.yaml#L41

I don't think there's an option for `--process-on-blank-line` yet though

**Comment by fivestones** [comment]
@krisgesling Thanks that's very helpful!
Maybe I should make a feature request for --process-on-blank-line for the api?

**Comment by krisgesling** [comment]
Yeah that would be good to have a distinct feature request - thanks!

**Comment by JohnSmithToYou** [comment]
I'm not sure if this is related but the UI can't seem to populate the "language", "name", and "speaker" fields. As a results the UI doesn't work at all. 
The client is getting a 500 from http://localhost:59125/api/voices

The server error:
```
ERROR:mimic3_http.app:Object of type set is not JSON serializable
Traceback (most recent call last):
  File "/home/jstraub/src/mimic3/.venv/lib/python3.10/site-packages/quart/app.py", line 1673, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/jstraub/src/mimic3/.venv/lib/python3.10/site-packages/quart/app.py", line 1718, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
  File "/home/jstraub/src/mimic3/.venv/lib/python3.10/site-packages/mimic3_http/app.py", line 269, in api_voices
    return jsonify(voice_dicts)
  File "/home/jstraub/src/mimic3/.venv/lib/python3.10/site-packages/quart/json/__init__.py", line 32, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/home/jstraub/src/mimic3/.venv/lib/python3.10/site-packages/quart/json/provider.py", line 205, in response
    return self._app.response_class(self.dumps(object_, **dump_args), mimetype=self.mimetype)
  File "/home/jstraub/src/mimic3/.venv/lib/python3.10/site-packages/quart/json/provider.py", line 171, in dumps
    return json.dumps(object_, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/jstraub/src/mimic3/.venv/lib/python3.10/site-packages/quart/json/provider.py", line 114, in _default
    raise TypeError(f"Object of type {type(object_).__name__} is not JSON serializable")
TypeError: Object of type set is not JSON serializable
```
I'm running it on Ubuntu 20.04 under Linux Subsystem for Linux.

@krisgesling As a workaround, is there client example (curl, python or something that can run in Windows) that can send text and receive a wav file?

**Comment by synesthesiam** [comment]
These issues are fixed in the `master` branch. Will push out a new package soon.

**Comment by traycerb** [comment]
I used the following instructions to get the master running, which fixed this bug: https://popey.com/blog/2022/10/setting-up-mimic3/

**Comment by tazz4843** [comment]
Still an issue today, no docker image exists with the fix yet.
